version: '3.1'

services:
  db:
    image: mongo:4.4
    restart: always
    container_name: short-url-db
    volumes:
      - db_data:/var/lib/mongodb/data
    networks:
      - short-url-net
  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - short-url-net
volumes:
  db_data:
networks:
  short-url-net:  
